### PR TITLE
Mystery Science Theater 3000 (MST3K) Channel

### PR DESCRIPTION
**Pull request by crowservo**
Note that I CANNOT post the requisite "[REL] MST3K" forum message BECAUSE of broken HTML on Plex's Website.  Specifically, the "Tell us why you want to join" page is broken:  
http://forums.plex.tv/entry/connect/jsconnect?client_id=1642210206
There is no valid input path available in the HTML, thus effectively blocking me from posting any forum message.  Tried in both Chrome/Win7 and FireFox/iOS (sans AdBlock etc) -- the Forum HTML appears to be just plain broken.
Feel free to create the "[REL] MST3K" forum message as you see fit, and maybe someday I can get thru above broken page.

### CODE REVIEW

**Comment by ukdtom** [comment]
Git must end with .bundle, så please rename the git

**Comment by ukdtom** [comment]
Ohh...And your html errors on the forums are 100% local, so please expand here on this

**Comment by crowservo** [comment]
Ok, repo renamed -- sorry I had .bundle as a folder, not top-level name.

On Plex Forum webpage, http://forums.plex.tv/ , three options (links) are available:

http://forums.plex.tv/entry/jsconnect?client_id=1642210206&Target=%2Fcategories
http://forums.plex.tv/entry/signin?Target=categories
http://forums.plex.tv/entry/register?Target=categories

All lead to:

http://forums.plex.tv/entry/connect/jsconnect?client_id=1642210206

At that page, there is only a single input control the user can interact with, a single button here:
<div class="Buttons"><div class="ButtonContainer"><input type="submit" id="Form_Connect" name="Connect" class="Button Primary" value="Connect">
</div></div>

Clicking the button simply gives Error message ("Username is required") here:

<div class="Messages Errors">
<ul>
<li>Tell us why you want to join!</li>
<li>Username is required.</li>
</ul>
</div>

Note that Plex webpage already has username etc. (from client_id=1642210206) as well as obviously listed in Form tag itself (of the Form that the button is in):

<form method="post" action="/entry/connect/jsconnect?client_id=1642210206">
<div>
<input type="hidden" id="Form_TransientKey" name="TransientKey" value=""><input type="hidden" id="Form_hpt" name="hpt" value="" style="display: none;"><input type="hidden" id="Form_JsConnect" name="JsConnect" value="uniqueid=11788674&amp;name=scooby138&amp;email=scooby138%40getnada.com&amp;roles=Members&amp;clientid=1642210206&amp;signature=a5149ba4feebcbb07bc361e738affe37ae127eff8097afa62dc3176dd2de10f7">
...

The Form appears to be broken.  I could write this off on the client browser, but this appears by on Win7/Chrome and iOS/Firefox.  I could spend time debugging your html but I prefer not to.  If the Plex webpage Form is throwing off above "Username is required" at the exact same time that said Form clearly already has captured that info in attributes, would appear that the Form may be broken under certain conditions.

Cheers.

**Comment by ukdtom** [comment]
Cried out for help here from Plex, and the response was:

`Might be a Vanilla problem, but we need the Plex account username/email to be able to look into this`

**Comment by crowservo** [comment]
Said username/email etc is already above, in the Form (and excerpted here for your convenience):

`name=scooby138&amp;email=scooby138%40getnada.com&amp;roles=Members&amp;clientid=1642210206&amp;signature=a5149ba4feebcbb07bc361e738affe37ae127eff8097afa62dc3176dd2de10f7"`

If one knows what exactly needs to be posted, I could just rip it in with GreaseMonkey, but easier for me if I just give you my password and have you create the trivial form stub message (or similar):  

[REL] MST3K
Coming soon ...

**Comment by sander1** [comment]
> This plug-in relies on crowd-source URLs at club-mst3k.com (usually YouTube). Note that when a link is bad, the Plex-provided YouTube URL Service does not handle it gracefully and returns "Channel not responding." I played around with writing my own YouTube URL Service but PMS seems to be hard coded to give preference/precedence to its own matching URL Services (so I cannot fix).

You can add a check to make sure a URL Service exists for a certain URL:

```
for videoItem in videoList:

    # Check for existing URL Service, skip entry if none is found.
    if not URLService.ServiceIdentifierForURL('http://...........'):
        continue
    else:
        oc.add(VideoClipObject(..............))
```

**Comment by ukdtom** [comment]
Plex looked into this.....Please try again, and also clearing of cookies/cache towards the forum and plex.tv might be needed.

**Comment by crowservo** [comment]
Ok, Plex Forum now fixed and I was able to post:  [REL] MST3K - Mystery Science Theater 3000
I have edited supporturl to list:  http://forums.plex.tv/discussion/251387/rel-mst3k-mystery-science-theater-3000/

**Comment by ukdtom** [comment]
Thanks.

**Pull request merged**
