### PR TITLE
Add PlexCasts to directory

### PR DESCRIPTION
**Pull request by adrianjones**

### CODE REVIEW

**Comment by sander1** [comment]
Hi @adrianjones! Is this the same/a similar fork like https://github.com/piplongrun/plexpod.bundle?

**Comment by ukdtom** [comment]
Awaits merge until we get a response to above Q

**Comment by ukdtom** [comment]
Closed due to lack of response

**Comment by adrianjones** [comment]
Sorry for no response.  My email was set incorrectly so I never saw it.
@sander1 - Yes, it is a fork of https://github.com/piplongrun/plexpod.bundle, but I updated the UX, layout and database (to include additional fields).  Additionally I have added @coryo DumbTools to it, so you can use it in a web browser too.
@ukdtom - If it is still possible, are you able to merge it in? If not can I create a new request?

**Pull request closed without merging**
