### PR TITLE
Remove ArconaiTV and PrimeWire

### PR DESCRIPTION
**Pull request by piplongrun**
Breaking all the time and too many complaints from users. Not worth it.

### CODE REVIEW

**Comment by Twoure** [comment]
Yup, I hear ya...

**Comment by Captnhook** [comment]
Understood. I for one really appreciated all of your work and thank you very much.
ArconaiTV to this day has never given me any problems and remains an awesome channel.
I understand PW's constantly changing host sites always breaking things.
It was good while it lasted. Thanks

**Comment by SRTDRE76** [comment]
man hate to see your work gone because of the few troublesome, well I can imagine more than a few, but here me out and give thought to my idea cause I for one appreciated each and every second you put into your work and understand programming is not easy, dabbed into it a little in university but it wasn't for me, so here is my idea. In order for users to complain to you and post they need to login right, well you then have there id's right can't you write these foolish troublemakers, headaches, whatever you want to call them into a ban list so they can not use your work ever? There has to be more appreciative users than complainers. Complaining about a free lunch and you deserve a public lashing far as I am concerned. Hope you consider the idea just to have a haha last say sorely for those who angered you into pulling your work, hope I see a return cause your stuff was / is plex server man, the few ruined everything for the thankful

**Comment by katzplay1** [comment]
My heart is broken. Its us who never complain that have to pay the price of those who whine. :( I will miss primewire, it used it all the time and understood the glitches.

**Comment by jkfifth** [comment]
Very sad to see this channel go. Thanks for all you did, piplongrun!

**Comment by kathyb585** [comment]
Nooooo....Primewire was the best channel! It was the only one I watched because it was the most reliable. So upset to see this one go. Thank you for all you did.

**Comment by piplongrun** [comment]
I put Arconai back up at https://github.com/piplongrun/arconaitv.bundle, but 0% support from now on.

**Pull request merged**
