### PR TITLE
Adds Adult DVD Empire metadata agent to UAS.

### PR DESCRIPTION
**Pull request by jesperrasmussen**
The metadata agent allows for scraping of metadata, posters and cast of adult movies, by searching adultdvdempire.com

### CODE REVIEW

**Comment by ukdtom** [comment]
So sorry, but without a support link to the forums, I can't merge this.

From the Wiki:

`Note In order to accept a PR, you have to fill out the support url link with a valid link, that points towards a thread with a name of: "[REL] your channel title". This thread has to be located in the Plex Channels Forum

Reason for doing this, is to avoid our support thread for getting flooded with support questions about your channel`

So please create a thread, and add to the PR already created

**Comment by jesperrasmussen** [comment]
Damn, sorry I missed that in the list of things to do beforehand - I'll do that right away :)

**Comment by jesperrasmussen** [comment]
And the support URL has now been added :)

**Comment by ukdtom** [comment]
And already added to https://forums.plex.tv/discussion/200017

So go ahead and edit the first post telling people, that it's now a full member of UAS ;-)

**Pull request merged**
