### PR TITLE
Added "Trakt.tv" plugin

### PR DESCRIPTION
**Pull request by fuzeman**
Hopefully this addition looks alright.

It's great to see UAS is back :smiley:

[Review on Reviewable](https://reviewable.io/reviews/ukdtom/uas2res/5)

### CODE REVIEW

**Comment by ukdtom** [comment]
Really would love an official support thread in the forums, as outlined in the wiki, since I fear they instead end up in the UAS thread :-(
Regular user will not go to GitHub....
Heck, some even have trouble with the forums, and it's scattered all over the place :-(
https://forums.plex.tv/discussions/tagged/trakt/p1

**Comment by fuzeman** [comment]
Kinda prefer GitHub for support :smile:, but I understand your point.

Will update this PR later tonight.

**Comment by fuzeman** [comment]
I've amended the commit: 183ca66541d1b00d4f02d98aeb69efc2656c2155

**Comment by ukdtom** [comment]
Thanks for understanding here ;-)
Will mere as soon as we update.
And speaking of.....Do you want your branch stuff to go with that release, or a later one, cuz we are about to fire up our beta tester crew ;-)

**Comment by fuzeman** [comment]
> And speaking of.....Do you want your branch stuff to go with that release, or a later one, cuz we are about to fire up our beta tester crew ;-)

I haven't had time to start on https://github.com/dagalufh/WebTools.bundle/issues/120 as I've still got a lot of work to finish for the Trakt.tv plugin update, probably best to leave that feature for a future update :smiley:

**Comment by JourneyOver** [comment]
Any idea on when this is being added to the webtools? :s

**Comment by ukdtom** [comment]
As soon as the next version of WebTools is released, since it depends on a fix in that, before working

**Comment by inquam** [comment]
I'm checking this every day... please release before I go crazy :). I have paused all my viewing of series and movies for the broken support for the old trakt plug in when I reinstalled my server and plex. :p

**Comment by ukdtom** [comment]
Heh, but still awaits for a few tweeks for the http part.
And then into beta once more.

But, and with no strings attached here, hopefully within the next 3 weeks

/T

**Comment by gyusza** [comment]
Hey all, before I mess it up :) Am i right to assume that just by downloading and placing the .bundle in the plugins folder, and restarting Plex, I can install this on my mac, similar to the windows approach?

**Pull request merged**
