### PR TITLE
Added Wake on LAN (WOL) Plugin for Plex

### PR DESCRIPTION
**Pull request by SpacemanJT**
Leave a comment

### CODE REVIEW

**Comment by jaminroe** [comment]
Oh wow awesome!

**Comment by ukdtom** [comment]
Thanks, and added to Support thread as well.

Remember to update the first post in the support thread saying it's avail in the UAS

**Comment by SpacemanJT** [comment]
Thanks, I've edited the Post in Plex.

Looking at the UAS I can see the Plugin is now available, however the Support link just has a dash in it. Can you fix this please? The support URL was in the JSON file. 

Thanks again.

**Comment by ukdtom** [comment]
Sorry, I missed, that you put an unwanted space in the variable "supporturl"

Fixed now, but you might have to wait some time, unsure here, for it to make it to your uas, since I'm investigating some github timestamp issues as well

/dane22

**Comment by SpacemanJT** [comment]
Thanks :D

**Pull request merged**
