### PR TITLE
Adding UAS Viewer

### PR DESCRIPTION
**Pull request by vanstinator**
So I saw some people wishing the new store had a plex channel UI, so I built one on top of your API this evening. I'll be fleshing it out in the next few days, but this should increase interest in the UAS overall going forward I would think. Anyway I need sleep, hope this merges better than last time :)

### CODE REVIEW

**Comment by ukdtom** [comment]
Hmmmmm.......One of the security checks that's build into WebTools, is that it only allows the owner of the PMS to access it.

You are with this plugin storing the owner credentials in the prefs, meaning that if one of your users get's access to this channel, they'll bypass that check!

So humbly suggest, that a huge warning get's put in somewhere, cuz would hate to see our UAS thread bombarded with posts about "random deletion/addition" of channels!

Besides that, just tried it out, and it failed to import "requests" module?

**Comment by vanstinator** [comment]
Ok I'll do that, makes perfect sense.

As far as having a channel fail can you send me a copy of the log? Been doing a lot of testing and channel installs, at least for me, are quite reliable. That said I fully expect bugs due to the straight burn I did to get this written last night

**Comment by vanstinator** [comment]
On another note right now I'm caching the UAS data during ValidatePrefs because I don't want to hit your services too hard if people start downloading this. Are there any other data limits I should be aware of as I build this?

**Comment by ukdtom** [comment]
Log file: https://gist.github.com/ukdtom/c2b719521cff560b4cef

And I think/hope my API can handle the pressure though.

/T

**Comment by vanstinator** [comment]
I've seen this happen myself before. It's like Plex starts the plugin before the files have settled to disk. My bet would be a PMS restart would solve it in this case, but ideally it would be good to have this just work. I'll add some error handling around this to restart the plugin if it doesn't find this.

**Comment by ukdtom** [comment]
But.....

The request module, AFAIK, is NOT part of python 2.7, thus while it fails, or?

/T

**Comment by ukdtom** [comment]
https://www.codecademy.com/forum_questions/510ac1a07390b897a8001574

**Comment by vanstinator** [comment]
I have it included in my git repo, so it should just p.... wait.... *facepalm/desk/wall.

One sec, I need to commit requests.

**Comment by vanstinator** [comment]
Again with the up late trying to release something :)

**Comment by ukdtom** [comment]
:-D

**Comment by vanstinator** [comment]
Try again good sir

**Comment by ukdtom** [comment]
Closing here, 

Do create a new PR, when more stable, as well as some kind of warning is added ;-)

**Pull request closed without merging**
