### PR TITLE
KissNetwork and LihatTV

### PR DESCRIPTION
**Pull request by Twoure**
Hi,
Thanks for getting the UAS2 up and running.  I've added my two channels KissNetwork and LihatTV into the merge.

Thanks again,
Twoure

### CODE REVIEW

**Comment by Twoure** [comment]
FYI, LihatTV does have an adult section which includes porn.  So maybe it should be flagged as adult too, but not sure since it's not the entire channel.

**Comment by ukdtom** [comment]
Hmmm......The Kiss one failed to load on my QNAP?

/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/KissNetwork.bundle/Contents/Modules
---^^^^---added to sys.path---^^^^---
----------By domain.pys----------
2016-01-15 08:33:58,815 (-b5d7470) :  INFO (domain:115) - loading domain dict in json format
2016-01-15 08:33:58,999 (-b5d7470) :  CRITICAL (services:441) - Error loading shared code (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/services.py", line 435, in _setup_shared_code_sandbox
    sandbox.execute(code)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "<shared>", line 3, in <module>
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/root/Library/Plex Media Server/Plug-ins/KissNetwork.bundle/Contents/Services/Shared Code/headers.pys", line 22, in <module>
    import cfscrape
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
RuntimeUnavailable: Could not find a JavaScript runtime.

2016-01-15 08:33:59,005 (-8e6f530) :  CRITICAL (core:615) - Exception starting plug-in (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/root/Library/Plex Media Server/Plug-ins/KissNetwork.bundle/Contents/Code/__init__.py", line 12, in <module>
    Headers = SharedCodeService.headers
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-26325ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/servicekit.py", line 86, in __getattr__
    raise Framework.exceptions.FrameworkException('No shared code object named "%s" was found.', name)
FrameworkException: ('No shared code object named "%s" was found.', 'headers')

**Comment by Twoure** [comment]
Yes I have another user who is also having issues using this with QNAP.  It requires Java to run, and I'm not sure how java is handle with the QNAP.  If you have any insights that would be wonderful.

**Comment by ukdtom** [comment]
Path is okay, and Java is not part of a std. QNAP, and only exists in upsupperted, and kinda old versions :-(

**Comment by ukdtom** [comment]
http://forum.qnap.com/viewtopic.php?t=112473#p492639

**Pull request merged**
