### PR TITLE
Added libupdater

### PR DESCRIPTION
**Pull request by Hellowlol**
Its kinda beta but it should work. :D Or it has in the small test that i have run.

### CODE REVIEW

**Comment by ukdtom** [comment]
Sorry, but to accept this, we, as outlined in the Wiki, need a [REL] thread in the plugins forum of Plex forums!

**Comment by Hellowlol** [comment]
I’m sorry I failed to read the wiki. I’ll make a thread and update the pr later

**Comment by ukdtom** [comment]
Also miss the icon file ;)

**Comment by Hellowlol** [comment]
https://forums.plex.tv/discussion/299457/rel-libupdater/ <- dont have time to update pr. im just to lazy to look for it later.

**Comment by ukdtom** [comment]
Then I'll wait ;)

Currently, you want to push to UAS, but doesn't provide users with the means to use your work!

As such, closing for now, and do feel free to recreate, when you sorted things out!

**Comment by ukdtom** [comment]
And Windows only thing I guess?
Based on:
`scannerpath = r'C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Scanner.exe'
You NEED to specify that in the description, as well as in your thread as well!

And you did see this one, already in the UAS, right?
https://github.com/mikedm139/LibraryUpdater.bundle

**Comment by Hellowlol** [comment]
I have only tested on windows and Ubuntu. There’s a option to add the path to the media scanner if it does not work with the default path. 

I have seen that (and use some code from it regarding scanning sections. In my version you can pretty much do the same as the cli tool that plex uses. But I have also simplified it you can just provide a path and the added will add missing info like section number that are required by the cli to work.

**Comment by ukdtom** [comment]
Ack....

And not wanted to be a turnoff here...Simply protecting UAS, so the plugins, put into it, has a bare minimum of instructions...

After all...WebTools/UAS has a total of +354.000 users, and most of them not knowing anything about IT.

As such, a bare documentation is a req.

**Pull request closed without merging**
