### PR TITLE
New Adult DVD Empire Metadata Agent

### PR DESCRIPTION
**Pull request by naguar**
Change to new version URL. Old agent has not been updated for very long and missed a lot of content due to source page changes and agent often failed with error which made scrape function unstable and metadata got update to 50% complete per title. Also added functionality, cast photos, director and genres.

### CODE REVIEW

**Comment by ukdtom** [comment]
Sorry, but don't understand why you didn't make a PR against the https://github.com/jesperrasmussen/AdultDVDEmpire.bundle git?

After all, it's his idea and work you forked

**Comment by naguar** [comment]
jesperrasmussen seem to have left it hanging for the last 8 month that is why I didnt PR. It's not jesperrasmussen idea, this the original one came from https://github.com/AndieUK/AdultDVDEmpire.bundle . 

Anyway I will keep the new fork alive and if you want to wait for a response from jesperrasmussen. I only see it as AndieUK who left it for years.

**Comment by ukdtom** [comment]
I'll wait for 5 days, and if no result, then you are the new master ;)

**Comment by naguar** [comment]
Its been 10 days and haven't heard anything yet.

**Comment by ukdtom** [comment]
Done, post: https://forums.plex.tv/t/support-find-my-plug-in-here-for-support-read-me-first/128698 updated, and added a post here a well: https://forums.plex.tv/t/rel-adult-dvd-empire/182012/10?u=dane22

**Pull request merged**
