### PR TITLE
Adding a channel to watch videos on 4tube

### PR DESCRIPTION
**Pull request by bagotx**

### CODE REVIEW

**Comment by ukdtom** [comment]
I need a support URL before I can accept this

**Comment by bagotx** [comment]
I thought this was called the **Unsupported** App Store for a reason. Added a support url anyway.

**Comment by ukdtom** [comment]
From the Wiki:

`Note In order to accept a PR, you have to fill out the support url link with a valid link, that points towards a thread with a name of: "[REL] your channel title". This thread has to be located in the Plex Channels Forum`

**Comment by bagotx** [comment]
Ok I created the plex forum discussion and also added the icon.

**Comment by ukdtom** [comment]
Sorry for all the mess here, but need to keep things as outlined, due to end users not knowing their way on GitHub.

Great work BTW ;-)

**Comment by ukdtom** [comment]
And FUI:

It's called Unsupported due to the fact, that it's not in the official channel directory
Reason why I demand a support thread is, that without one, my UAS/WebTools thread will be swarmed with support req. for channels in the UAS, and I do NOT want that

**Pull request merged**
