### PR TITLE
Renamed C More LIVE -> C More Sport. Also made icon symmetric(=square).

### PR DESCRIPTION
**Pull request by JeppeTh**
No big deal, no rush...

### CODE REVIEW

**Comment by ukdtom** [comment]
Please update your rel post to reflect, that it's avail in UAS2 :-)

**Comment by JeppeTh** [comment]
I assumed that "unsupported app store" meant UAS2 to all plex users - but I can be extra clear.
Thx.

**Comment by JeppeTh** [comment]
Or perhaps you meant that I should make it clear it really is available now.
Done that as well ;-)

**Comment by ukdtom** [comment]
Last was what I meant ;-)

And perfect, and following the Wiki:

> Opening [REL] Support form thread

After your work has been accepted by UAS2, you should alter/edit your opening post to let your users know, that they can install via UAS2

**Pull request merged**
