### PR TITLE
Adding NextPVR Channel

### PR DESCRIPTION
**Pull request by psyciknz**
Hopefully I've done this right, but I restructured the project, renamed the repository to get it ready for this UAS pull

### CODE REVIEW

**Comment by ukdtom** [comment]
Before I merge, did you notice, that if you add a zip file to your release, you can get UAS2 to download that instead, by setting the `release` property in the json

`    {
        "title"           :     "ExportTools",
        "bundle"          :     "ExportTools.bundle",
        "type"            :     ["Application"],
        "description"     :     "Will export selected sections into a CSV or xlsx file",
        "repo"            :     "https://github.com/ukdtom/ExportTools.bundle",
        "branch"          :     "master",
        "release"         :     "ExportTools.bundle.zip",
        "DeleteCacheDir"  :     false,
        "DeleteDataDir"   :     false,
        "identifier"      :     "com.plexapp.plugins.ExportTools",
        "icon"            :     "icon-exporttools.png",
        "supporturl"      :     "https://forums.plex.tv/discussion/254248",
        "popupmsg"	      :	    "This tool is a replacement for Plex2CSV. If Plex2CSV is installed, please uninstall it. To see further info, look here: https://github.com/ukdtom/ExportTools.bundle/wiki",
				"manual"					:			"https://github.com/ukdtom/ExportTools.bundle/wiki"
    },`


Doing so, enables you to get download count_counts about your work, like:
https://api.github.com/repos/ukdtom/ExportTools.bundle/releases/latest

Also, you can add nice badges to the readme.md like I did for ExportTools

Also, the currently undocumented key named `popupmsg` will in the next version of WebTools be active, and will show the user a msg. after a successful install (Like you can point users to the other bundles in this combo)

**Comment by psyciknz** [comment]
No I didn't notice that.  I just took a json entry from the bittorrent entry.  So didn't really investigate the entire format.

So the zip file name is the one it makes upon tagging a release?  And the zip file will be the released version?  (ie not the latest if I've done a commit since the release)

I've not played with releases much but did that for the first time last night.

**Comment by ukdtom** [comment]
After your master is ready, download it, extract it, nuke not relevant files, and zip again as <plugin-name>.bundle.zip

Then attach that like I did for my ExportTools

**Comment by ukdtom** [comment]
And as a golden rule, always look up my ExportTools json config, since it's kinda updated with the features of UAS...

And really should add that to the Wiki....SIGH....

**Comment by psyciknz** [comment]
Ok so I might switch to the .zip.  So I'm happy with the release zip as it stands.  I see in the release tagging the URL is : https://github.com/psyciknz/NextPVR.bundle/archive/0.5.zip

Is my zip file name 0.5.zip If I don't upload a new zip file?  Or is there some magic in the tool that changes it to NextPVR.bundle.zip

**Comment by ukdtom** [comment]
Don't use a version number for the zip file, since then you'll have to issue a PR against UAS Repo every time you release a new version.
Use a generic name like: NextPVR.bundle.zip

And when releasing a new version, use the same name

**Comment by ukdtom** [comment]
And you have to edit your release, and drag in the zip file to the "Binary files"

**Comment by psyciknz** [comment]
Ok I think I've done that right.   I edited the .json, and then did a new pull request.  Hopefully you can see it (or this one is updated)

**Comment by ukdtom** [comment]
Thanks

**Pull request merged**
