### PR TITLE
9anime - added new video channel

### PR DESCRIPTION
**Pull request by Twoure**

### CODE REVIEW

**Comment by Twoure** [comment]
Ugh, site just switched over to `https` and now the `ssl` error is showing up rendering this channel dead for now. :disappointed: .  Removing my pull request for the time being, until the site works out its ssl certs.

**Comment by jaminroe** [comment]
That sucks. I just found out about this site too

**Comment by Twoure** [comment]
@jaminroe 
[KissNetwork](https://github.com/Twoure/KissNetwork.bundle) still works.  Plex Forum support link [[REL] KissNetwork](https://forums.plex.tv/discussion/186988/rel-kissnetwork/p1#Discussion_186988), and it's already within Webtools.

**Comment by Twoure** [comment]
Fixed channel, and planning to improve it some more.

**Comment by Twoure** [comment]
Sorry, will update my repo and fix merg request

**Pull request closed without merging**
