### PR TITLE
Add MYTF1 plugin

### PR DESCRIPTION
**Pull request by tuxity**
I'm adding my plugin to the UAS to watch all replays from tf1.fr website.
Everything should be okay

### CODE REVIEW

**Comment by ukdtom** [comment]
Thanks mate.

Remember to tell in the first post/GitHub, that it now is avail in UAS2

**Comment by tuxity** [comment]
@ukdtom oups I just saw there is a mistake in the icon filename, should be `icon-mytf1.jpg` NOT `icon-tf1.jpg`. Could you update it when you have 30 sec ? Or should I just made another PR ?

**Comment by ukdtom** [comment]
Please make another PR

**Comment by tuxity** [comment]
Done in #43

**Pull request merged**
