### PR TITLE
Add TFC - The Filipino Channel to UAS

### PR DESCRIPTION
**Pull request by magnuslsjoberg**
I have checked that the plugin works in UAS via manual install and think it is ready to go...

### CODE REVIEW

**Comment by ukdtom** [comment]
Cool, please remember to alter the opening post, to reflect it can be installed via the UAS

**Comment by magnuslsjoberg** [comment]
Thanks! I will update the info in the support thread.  I haven't used UAS / WebTools before and I must say it seems really useful. Installation and updates of plugins really simple even if they are not in UAS, really good log tool...

**Comment by ptfir** [comment]
@magnuslsjoberg I just saw the the plugin was removed from your repositories?

**Comment by magnuslsjoberg** [comment]
Yeah, sorry for that!   I will upload a new, NON WORKING, version so that others can take a shot at it, but I need to fix some small issues first...

**Comment by magnuslsjoberg** [comment]
@ptfir:

OK, repository back,   The plugin is NOT working yet but the login works,
Some more adjustment when retrieving the media info needed.

**Comment by ukdtom** [comment]
Please do your work in another branch than master, and when working, push to master.

Master is the branch you specified for the UAS, so it should only contain a working version!

**Comment by magnuslsjoberg** [comment]
Sorry, for that!

So what should I do when the plugin is broken by the website I am accessing?
I.e, no working plugin exists?

**Comment by ukdtom** [comment]
If a fix is in the pipeline, nothing except maybe post in the release thread.

If a fix is not in the pipeline, plugin should be considered abandoned, and a PR should be made against the UAS repo, reverting the changes that was made to add it

**Comment by magnuslsjoberg** [comment]
Thanks!

I have paused the plugin and removed it from UAS and updated the release thread.
I am still not fully conversant with GitHub so I hope I got it right!

I really hope that I will get it up and running in the future and put it back in UAS (if Plex hasn't removed the plugin support before that...)

**Comment by ukdtom** [comment]
> I am still not fully conversant with GitHub so I hope I got it right!

Failed :)

For future ref, you need to pull from master, to get the latest version, then remove the lines you added to the json, as well as the icon in a new PR

When said, I'll take it from here, and remove it

**Pull request merged**
